= Perl 6 Style Guide
:toc: preamble

This is a styleguide for writing https://perl6.org/[Perl 6] code. It's still in
it's early stages, and feedback would be greatly appreciated. Also note that
this is a set of rules for https://scriptkitties.church[Scriptkitties]
projects, not necesarily for you.

== Indentation style
The preferred indentation style for Scriptkitties projects is to use **tabs**
for indention. If you need to *align* things, however, you should use spaces:

[source,perl6]
----
sub foo (
	%bar,
) {
	%bar<some-index>    = "Some string";
	%bar<another-index> = "Another string";
}
----

Aligning code is *not* required, but is allowed if you think it will improve
readability of the code.

== POD comments
Apply POD comments to your subs. A small description on the method should go
directly above it, and descriptions on the arguments should go above the
arguments themself:

[source,perl6]
----
#| A small description on the sub foo. This is returned on foo.WHY.
sub foo (
	#| What to expect of the bar argument
	Str:D $bar,
) is export {
	…
}
----

== Styles to avoid

* Avoid using $_, unless needed.
[source,perl6]
----
for @array -> $element { # good
	say $element;
}
for @array {
	.say # good
}
.say for @array; # better
----

* Declare constants with my, otherwise they are **automatically** *exported* by any module that uses it.
[source,perl6]
----
constant CONST = 10; # BAD
my constant CONST = 10; # good
